-- Longevity content upgrade: timing guidance, expanded content types, and reviewed Spanish seeds.

alter table public.longevity_daily_content
  add column if not exists timing_guidance text;

alter table public.longevity_daily_content
  drop constraint if exists longevity_daily_content_content_type_check;

alter table public.longevity_daily_content
  add constraint longevity_daily_content_content_type_check
  check (content_type in (
    'exercise', 'meal', 'tip', 'article', 'supplement', 'natural_solution'
  ));

-- Replace the generic starter set. New rows stay inactive until admin review/activation.
update public.longevity_daily_content
set is_active = false;

insert into public.longevity_daily_content
  (content_type, title, description, detail_text, timing_guidance, source_label, source_url, condition_tags, pillar_tag, time_of_day, language, rotation_weight, is_active)
values
('exercise',
 'Caminata Zona 2 tras comer - 10 min',
 'Una caminata suave despues de comer ayuda a moderar el pico de glucosa y suma movimiento cardiovascular sin convertir el dia en una rutina larga.',
 'Sal a paso comodo en los 30 minutos siguientes a comer. Zona 2 significa que puedes hablar sin quedarte sin aire. Si llueve, 100 pasos en casa o por el pasillo mantienen el objetivo practico.',
 'Dentro de los 30 min tras comer',
 null, null, array['heart','diabetes','all'], 'heart', 'any', 'es', 4, false),
('exercise',
 'Equilibrio en un pie junto a la encimera',
 'El equilibrio de una sola pierna es una senal util de fuerza, coordinacion y seguridad al caminar; entrenarlo poco y a menudo puede reducir tropiezos.',
 'De pie junto a una encimera, apoya la yema de los dedos. Levanta un pie durante 10-20 segundos, cambia de lado y repite tres veces. Mantente cerca de apoyo estable.',
 'Cualquier momento, junto a apoyo firme',
 null, null, array['falls','strength','all'], 'strength', 'any', 'es', 4, false),
('exercise',
 'Respiracion 4-7-8 - 3 min',
 'Un patron de exhalacion larga ayuda a bajar revoluciones y puede apoyar el descanso, especialmente cuando el cuerpo esta activado al final del dia.',
 'Inhala por la nariz 4 tiempos, mantente 7 si te resulta comodo y exhala lentamente 8. Haz 3-4 ciclos. Si contener el aire incomoda, usa 4 dentro y 6 fuera.',
 'Mejor por la noche o al despertar',
 null, null, array['anxiety','heart','all'], 'calm', 'any', 'es', 4, false),
('exercise',
 'Fuerza sentado - 12 min',
 'Despues de los 65, mantener musculo ayuda a proteger autonomia, equilibrio y control de glucosa. Una silla firme basta para empezar.',
 'Haz elevaciones de rodilla, press de manos contra la mesa, circulos de hombro y levantarte/sentarte lento. Mantente en esfuerzo comodo y para si aparece dolor.',
 'Por la manana o al mediodia',
 null, null, array['falls','strength','all'], 'strength', 'morning', 'es', 3, false),
('exercise',
 'Luz natural matutina - 10 min',
 'La luz exterior por la manana ayuda a sincronizar el reloj corporal, lo que suele apoyar energia diurna y sueno nocturno.',
 'Sal a balcon, portal o calle en la primera hora tras levantarte. No hace falta sol directo. Si no puedes salir, acercarte a una ventana luminosa es una version pequena.',
 'Primera hora tras levantarte',
 null, null, array['sleep','all'], 'calm', 'morning', 'es', 4, false),
('exercise',
 'Movilidad de cadera y psoas - 5 min',
 'Muchas horas sentado acortan la parte frontal de la cadera, lo que puede cambiar la zancada y hacer caminar menos natural.',
 'Da un paso largo hacia delante y sujeta una silla. Dobla suavemente la rodilla delantera hasta notar apertura en la cadera trasera. Mantiene 20-30 segundos por lado.',
 'Antes de caminar o por la manana',
 null, null, array['falls','strength','all'], 'strength', 'morning', 'es', 2, false),
('exercise',
 'Final fresco de ducha - 20 segundos',
 'Un breve cambio de temperatura puede activar atencion y respiracion. Debe sentirse fresco y manejable, no como una prueba de resistencia.',
 'Termina la ducha con 20 segundos de agua fresca, respirando lento. Evitalo si te marea, si tienes malestar o si tu medico te ha indicado evitar cambios bruscos de temperatura.',
 'Al terminar la ducha habitual',
 null, null, array['all'], 'calm', 'morning', 'es', 2, false),
('exercise',
 'Caminata de atencion plena - 12 min',
 'Combina movimiento suave con estimulacion cognitiva: notar el entorno hace que caminar sea tambien un ejercicio de orientacion y memoria.',
 'Camina sin auriculares y nombra mentalmente 5 cosas que ves, 3 que escuchas y 2 sensaciones fisicas. La meta es presencia, no distancia.',
 'A cualquier hora, sin prisas',
 null, null, array['alzheimers','anxiety','brain','all'], 'brain', 'any', 'es', 3, false),
('exercise',
 'Tobillos despiertos antes de salir',
 'Los tobillos ayudan a corregir pequenos desequilibrios. Activarlos antes de caminar puede hacer la primera parte del paseo mas estable.',
 'Sentado, dibuja 10 circulos con cada pie, luego sube y baja puntas 12 veces. Si usas baston o andador, hazlo antes de ponerte de pie.',
 'Antes de caminar',
 null, null, array['falls','mobility','all'], 'strength', 'any', 'es', 3, false),
('exercise',
 'Escaleras suaves, solo si son seguras',
 'Subir pocos escalones activa piernas y corazon de forma funcional, parecida a lo que la vida diaria exige.',
 'Usa barandilla. Sube 4-8 escalones a ritmo tranquilo y baja despacio. Si hay dolor, mareo o poca estabilidad, cambia por sentarse y levantarse de una silla.',
 'Mediodia, con buena luz',
 null, null, array['heart','strength','all'], 'heart', 'afternoon', 'es', 2, false),

('meal',
 'Aceite de oliva virgen extra - 2 cucharadas',
 'El aceite de oliva virgen extra aporta polifenoles ligados a salud cardiovascular en patron mediterraneo. La clave es usarlo crudo y suficiente.',
 'Anadelo sobre ensalada, verduras, pescado o pan. Medir dos cucharadas ayuda porque solemos subestimar la cantidad. Evita quemarlo para conservar mejor aroma y polifenoles.',
 'Crudo, sobre el plato ya servido',
 null, null, array['heart','all'], 'heart', 'any', 'es', 4, false),
('meal',
 'Sardinas con tomate y limon',
 'Las sardinas combinan omega-3, vitamina D y calcio en una comida sencilla. Es una opcion practica cuando no apetece cocinar.',
 'Elige sardinas al natural o en aceite de oliva. Sirve con tomate, limon y pan integral. Si vigilas sodio, revisa la etiqueta y escurre la conserva.',
 'Comida o cena ligera',
 null, null, array['heart','brain','all'], 'heart', 'any', 'es', 3, false),
('meal',
 'Arandanos o frutos rojos en el desayuno',
 'Los frutos rojos aportan polifenoles relacionados con salud vascular y cognitiva. Congelados tambien sirven y suelen ser mas faciles de tener en casa.',
 'Anade un punado a yogur natural, avena o queso fresco. Color intenso suele indicar mas antocianinas. Evita versiones azucaradas.',
 'Desayuno o media manana',
 null, null, array['brain','alzheimers','all'], 'brain', 'morning', 'es', 4, false),
('meal',
 'Huevos enteros para colina',
 'La yema aporta colina, nutriente importante para memoria y funcion muscular. Para muchas personas mayores, el desayuno es donde falta proteina.',
 'Prepara uno o dos huevos cocidos, revueltos o a la plancha. Si tu medico te ha limitado huevos por un motivo concreto, sigue esa indicacion.',
 'Desayuno, sin retirar la yema',
 null, null, array['brain','strength','all'], 'brain', 'morning', 'es', 3, false),
('meal',
 'Siete mitades de nuez',
 'Las nueces aportan grasas insaturadas, fibra y polifenoles. Una racion pequena puede mejorar la calidad del tentempie sin complicar la dieta.',
 'Come unas 7 mitades solas o con yogur. Mejor naturales que tostadas o saladas. Si tienes dificultad para masticar, picarlas fino ayuda.',
 'Media manana o media tarde',
 null, null, array['heart','brain','all'], 'heart', 'any', 'es', 3, false),
('meal',
 'Caldo con jengibre por la noche',
 'Una bebida caliente y salada-suave puede ayudar a cerrar el dia y aporta una forma facil de hidratacion y confort.',
 'Calienta una taza de caldo bajo en sal y anade jengibre rallado. Si tienes restriccion de liquidos o sodio, adapta cantidad segun indicacion medica.',
 '30-60 min antes de dormir',
 null, null, array['calm','all'], 'calm', 'evening', 'es', 2, false),
('meal',
 'Curcuma con pimienta y aceite',
 'La curcuma se aprovecha mejor acompanada de grasa y pimienta. En la practica, funciona mejor como pequeno habito culinario que como promesa aislada.',
 'Mezcla media cucharadita de curcuma, pizca de pimienta negra y aceite de oliva en verduras, sopa o arroz. Evitala en dosis altas si tomas anticoagulantes sin comentarlo con tu medico.',
 'Con comida que lleve aceite',
 null, null, array['heart','nourishment','all'], 'nourishment', 'any', 'es', 3, false),
('meal',
 'Lentejas con verduras',
 'Las legumbres combinan proteina vegetal, fibra y minerales. Son una base de longevidad porque alimentan musculo y microbioma a la vez.',
 'Cocina lentejas con zanahoria, cebolla, apio y ajo. Termina con aceite de oliva crudo y pimenton. Si te hinchan, empieza con media racion.',
 'Plato principal a mediodia',
 null, null, array['heart','diabetes','all'], 'nourishment', 'afternoon', 'es', 3, false),
('meal',
 'Yogur griego natural con canela',
 'Aporta proteina facil y puede encajar bien cuando el apetito es bajo. La canela da sabor sin depender de azucar.',
 'Usa yogur natural sin azucar. Anade canela, frutos rojos o nueces. Si tienes intolerancia a lactosa, prueba version sin lactosa o kefir si lo toleras.',
 'Desayuno o merienda',
 null, null, array['strength','nourishment','all'], 'nourishment', 'any', 'es', 3, false),
('meal',
 'Garbanzos con pimenton y aceite',
 'Una pequena racion de garbanzos suma fibra, saciedad y proteina vegetal. Es comida real que se prepara en minutos.',
 'Enjuaga garbanzos cocidos, calienta con pimenton, ajo suave y aceite de oliva. Acompana con verduras para mejorar el plato sin hacerlo pesado.',
 'Comida rapida de mediodia',
 null, null, array['diabetes','heart','all'], 'nourishment', 'afternoon', 'es', 3, false),

('tip',
 'El musculo es seguro de independencia',
 'La masa muscular ayuda a levantarse, caminar, subir escalones y recuperarse de enfermedades. No es estetica: es autonomia.',
 'Hoy prioriza proteina en una comida y un gesto de fuerza pequeno. Si el desayuno es flojo, anadir huevo, yogur o legumbre puede cambiar el dia.',
 'Empieza por la proxima comida',
 null, null, array['strength','all'], 'strength', 'any', 'es', 4, false),
('tip',
 'Respirar lento antes de dormir',
 'La respiracion lenta favorece el tono vagal y puede ayudar a que el cuerpo entre en modo descanso.',
 'Pon una mano en el abdomen. Respira 5 segundos dentro y 5 fuera durante 5 minutos. No busques perfeccion: busca regularidad.',
 'Noche, antes de dormir',
 null, null, array['heart','anxiety','sleep','all'], 'calm', 'evening', 'es', 3, false),
('tip',
 'Doce horas sin picar por la noche',
 'Un descanso digestivo nocturno sencillo puede apoyar glucosa, sueno y rutina sin entrar en ayunos extremos.',
 'Si cenas a las 20:00, intenta desayunar despues de las 8:00. Agua o infusion sin azucar estan bien. Evitalo si tu medico te indico comer por medicacion o glucosa.',
 'Desde cena hasta desayuno',
 null, null, array['diabetes','sleep','all'], 'nourishment', 'evening', 'es', 3, false),
('tip',
 'Una voz familiar cuenta',
 'La conexion social no es un extra. Una conversacion breve puede mejorar animo, orientacion y constancia.',
 'Llama a alguien que te alegre durante 10 minutos. Mejor voz que mensaje. Si no sabes a quien, pide a VYVA preparar una llamada facil.',
 'Cualquier momento tranquilo',
 null, null, array['alzheimers','anxiety','calm','all'], 'calm', 'any', 'es', 4, false),
('tip',
 'Treinta plantas por semana',
 'La variedad vegetal alimenta diferentes bacterias intestinales. Cuenta fruta, verdura, legumbre, frutos secos, semillas, hierbas y especias.',
 'Hoy anade dos plantas nuevas al plato: perejil, ajo, pimenton, nueces, lentejas o arandanos tambien cuentan.',
 'Con una comida principal',
 null, null, array['nourishment','all'], 'nourishment', 'any', 'es', 3, false),
('tip',
 'El sueno profundo cuida memoria',
 'Dormir en horario regular ayuda al cerebro a consolidar recuerdos y limpiar residuos metabolicos.',
 'Elige una hora de acostarte y prepara la habitacion fresca y oscura. Siestas largas despues de media tarde pueden dificultarlo.',
 'Misma hora de dormir',
 null, null, array['alzheimers','sleep','brain','all'], 'calm', 'evening', 'es', 4, false),
('tip',
 'Paso vivo, no paso agotador',
 'La capacidad cardiorrespiratoria mejora con esfuerzo moderado repetido. No hace falta correr: basta caminar algo mas vivo si es seguro.',
 'Durante 10-20 minutos, camina a un ritmo donde puedas hablar en frases cortas. Si usas apoyo o te cansas, hazlo en intervalos de 2 minutos.',
 'Cuando haya buena luz y piso seguro',
 null, null, array['heart','mobility','all'], 'heart', 'any', 'es', 3, false),
('tip',
 'Sol de manana con prudencia',
 'La luz de manana ayuda al reloj corporal; la exposicion solar debe adaptarse a piel, estacion y consejo medico.',
 'Sal 10-15 minutos por la manana. Si tienes piel sensible, antecedentes de cancer de piel o medicacion fotosensible, prioriza sombra luminosa y consulta proteccion.',
 'Manana, antes del calor fuerte',
 null, null, array['sleep','all'], 'calm', 'morning', 'es', 2, false),
('tip',
 'Pausa de pie cada hora',
 'Romper periodos largos sentado ayuda a circulacion, espalda y glucosa. Es pequeno, pero se acumula durante todo el dia.',
 'Cada hora, ponte de pie 60 segundos y mueve tobillos u hombros. Si levantarte cuesta, haz primero 10 bombeos de pies sentado.',
 'Cada hora despierto',
 null, null, array['heart','diabetes','mobility','all'], 'heart', 'any', 'es', 3, false),
('tip',
 'Oir bien ayuda a participar',
 'Cuando oir requiere mucho esfuerzo, conversar cansa y el cerebro recibe menos estimulo social.',
 'Hoy revisa si audifonos, volumen o subtitulos estan listos para una conversacion o video. Es una accion pequena para memoria y conexion.',
 'Antes de llamada, TV o video',
 null, null, array['brain','social','all'], 'brain', 'any', 'es', 2, false),

('supplement',
 'Omega-3 con comida grasa',
 'EPA y DHA se asocian con apoyo cardiovascular y cognitivo. La absorcion suele mejorar cuando se toma con una comida que contenga grasa.',
 'Si usas omega-3, revisa que la etiqueta diga EPA+DHA, no solo "aceite de pescado". Si tomas anticoagulantes o tienes cirugia prevista, comentalo con tu medico.',
 'Con la comida mas grande del dia',
 null, null, array['heart','brain','all'], 'heart', 'any', 'es', 4, false),
('supplement',
 'Vitamina D3 con analitica',
 'La vitamina D baja es comun en mayores, pero conviene medirla cuando sea posible para ajustar dosis con criterio.',
 'Tomarla por la manana con grasa puede mejorar tolerancia. Pide a tu medico 25(OH)D si hay caidas, poca luz solar o fatiga persistente.',
 'Manana, con comida que lleve grasa',
 null, null, array['falls','strength','all'], 'strength', 'morning', 'es', 4, false),
('supplement',
 'Magnesio glicinato para rutina nocturna',
 'El magnesio participa en funcion muscular y nerviosa. La forma glicinato suele ser mejor tolerada que otras.',
 'Si lo usas, empieza bajo y observa digestion. Evitalo sin consulta si tienes enfermedad renal o tomas medicacion que pueda interactuar.',
 '30-60 min antes de dormir',
 null, null, array['anxiety','sleep','heart','all'], 'calm', 'evening', 'es', 4, false),
('supplement',
 'CoQ10 si hay estatinas en el plan',
 'La CoQ10 se relaciona con energia celular. Algunas personas que toman estatinas preguntan por ella cuando notan cansancio muscular.',
 'No cambies estatinas por tu cuenta. Si tomas estatina y hay molestias, lleva esta pregunta a tu medico: "Tiene sentido revisar CoQ10 o la dosis?".',
 'Con comida principal',
 null, null, array['heart','all'], 'heart', 'any', 'es', 3, false),
('supplement',
 'Creatina monohidrato para fuerza',
 'La creatina esta bien estudiada para fuerza y funcion muscular. En mayores puede ser util dentro de un plan de movimiento y proteina.',
 'Si tu medico la ve adecuada, 3 g diarios suelen ser suficientes para empezar. Bebe agua. Evitala sin consulta si tienes enfermedad renal.',
 'Con cualquier comida',
 null, null, array['falls','strength','brain'], 'strength', 'any', 'es', 2, false),
('supplement',
 'Melena de leon con expectativa realista',
 'La melena de leon se investiga por apoyo cognitivo, pero los efectos no son inmediatos ni sustituyen sueno, movimiento y conexion.',
 'Busca productos claros sobre extracto y dosis. Si tomas muchos medicamentos o tienes alergias a hongos, revisalo antes con profesional sanitario.',
 'Manana, con desayuno',
 null, null, array['alzheimers','brain'], 'brain', 'morning', 'es', 2, false),
('supplement',
 'Ashwagandha no es para todo el mundo',
 'Puede apoyar manejo de estres en algunas personas, pero tambien puede no encajar con tiroides, autoinmunidad o ciertos farmacos.',
 'Si te interesa, tratalo como pregunta para medico o farmaceutico, no como impulso. Empieza solo si es adecuado para tu historial.',
 'Noche si se usa para calma',
 null, null, array['anxiety','all'], 'calm', 'evening', 'es', 2, false),
('supplement',
 'B12 si tomas metformina',
 'La metformina puede reducir absorcion de B12 en algunas personas. Revisarla evita confundir cansancio u hormigueo con "solo edad".',
 'Pregunta por B12 en la proxima analitica si tomas metformina. La forma sublingual puede ser practica si hay problemas de absorcion.',
 'Manana, segun pauta profesional',
 null, null, array['diabetes','brain','all'], 'brain', 'morning', 'es', 4, false),
('supplement',
 'Berberina: solo con supervision si hay diabetes',
 'La berberina puede afectar glucosa y tambien interactuar con medicacion. Por eso no debe entrar como consejo automatico en un plan de diabetes.',
 'Si ya tomas medicacion para glucosa, no la anadas por tu cuenta. VYVA puede ayudarte a preparar la pregunta para tu medico.',
 'Antes de comidas solo si tu medico lo aprueba',
 null, null, array['diabetes'], 'nourishment', 'any', 'es', 2, false),
('supplement',
 'Fibra psyllium con mucha agua',
 'La fibra soluble puede apoyar regularidad intestinal, saciedad y colesterol dentro de una dieta completa.',
 'Empieza con poca cantidad y siempre con un vaso grande de agua. Separala 2 horas de medicacion para evitar interferir con absorcion.',
 'Con agua, separada de medicacion',
 null, null, array['heart','diabetes','nourishment','all'], 'nourishment', 'any', 'es', 3, false),

('natural_solution',
 'Manzanilla concentrada antes de dormir',
 'La manzanilla puede servir como senal corporal de cierre del dia y contiene apigenina, un compuesto estudiado por su relacion con calma.',
 'Usa 1-2 bolsitas y dejala reposar 5 minutos. Mantiene el ritual igual varios dias; el valor esta en repetir una senal sencilla.',
 '30 min antes de dormir',
 null, null, array['anxiety','sleep','all'], 'calm', 'evening', 'es', 3, false),
('natural_solution',
 'Jengibre fresco en agua o comida',
 'El jengibre aporta compuestos aromaticos relacionados con digestion y confort articular leve.',
 'Ralla 1 cm en agua caliente o anadelo al caldo. Si tomas anticoagulantes o tienes reflujo fuerte, empieza con poca cantidad y consulta si dudas.',
 'Manana o comida principal',
 null, null, array['nourishment','all'], 'nourishment', 'any', 'es', 3, false),
('natural_solution',
 'Cereza acida como ritual nocturno',
 'La cereza acida contiene pequenas cantidades naturales de melatonina y polifenoles. Puede encajar como ritual, no como solucion magica.',
 'Si la usas, elige zumo sin azucar anadido y toma poca cantidad. Evitala si no encaja con tu plan de glucosa.',
 '30-60 min antes de dormir',
 null, null, array['sleep','calm','all'], 'calm', 'evening', 'es', 2, false),
('natural_solution',
 'Contacto seguro con cesped o jardin',
 'Estar unos minutos en suelo natural puede bajar tension mental por atencion sensorial, luz y movimiento suave.',
 'Si tienes jardin o parque seguro, camina despacio o permanece de pie con calzado estable. Evita ir descalzo si hay riesgo de corte, caida o sensibilidad en pies.',
 'Manana, con superficie segura',
 null, null, array['calm','mobility','all'], 'calm', 'morning', 'es', 2, false),
('natural_solution',
 'Ajo reposado al final del plato',
 'El ajo aporta compuestos azufrados y sabor intenso, lo que puede ayudar a reducir sal sin perder satisfaccion.',
 'Macha un diente y dejalo reposar 10 minutos antes de anadirlo crudo o casi al final. Si te irrita el estomago, usa menos o cocinalo suave.',
 'Con comida, al final',
 null, null, array['heart','nourishment','all'], 'heart', 'any', 'es', 2, false),
('natural_solution',
 'Agua tibia con limon',
 'Puede ser una forma agradable de iniciar hidratacion. No cambia el pH del cuerpo, pero si puede ayudar a recordar beber temprano.',
 'Medio limon en agua tibia si te sienta bien. Usa pajita o enjuaga la boca despues si te preocupa el esmalte dental.',
 'Al levantarte',
 null, null, array['nourishment','all'], 'nourishment', 'morning', 'es', 3, false),
('natural_solution',
 'Lavanda como senal de descanso',
 'El olor familiar de lavanda puede ayudar a crear una asociacion de calma antes de dormir.',
 'Una gota en un panuelo cerca de la cama o una bolsita seca. Evita aceites esenciales directos sobre piel sensible.',
 'Dormitorio, 30 min antes de dormir',
 null, null, array['anxiety','sleep','all'], 'calm', 'evening', 'es', 2, false),
('natural_solution',
 'Melisa para una pausa de tarde',
 'La melisa se usa tradicionalmente para calma suave y digestion. El valor aqui es crear una pausa sin pantalla.',
 'Prepara una infusion y sientate 5 minutos sin movil. Si tomas sedantes o medicacion tiroidea, consulta antes de usarla a diario.',
 'Tarde, lejos de pantallas',
 null, null, array['anxiety','calm','all'], 'calm', 'afternoon', 'es', 2, false),
('natural_solution',
 'Compresa tibia para hombros tensos',
 'El calor local puede relajar musculatura y hacer mas facil respirar profundo o dormir.',
 'Aplica una toalla tibia en hombros 8-10 minutos. Debe estar agradable, no caliente. Revisa piel si hay sensibilidad reducida.',
 'Noche o despues de tension',
 null, null, array['calm','mobility','all'], 'calm', 'evening', 'es', 2, false),
('natural_solution',
 'Rutina de luz tenue',
 'Bajar intensidad de luz ayuda al cerebro a distinguir dia y noche, especialmente si el sueno esta irregular.',
 'Una hora antes de dormir, usa luces calidas y baja brillo de pantallas. Si ves television, activa subtitulos y evita volumen alto.',
 'Ultima hora antes de dormir',
 null, null, array['sleep','brain','all'], 'calm', 'evening', 'es', 3, false),

('article',
 'Capacidad cardiorrespiratoria y longevidad',
 'Mejorar un poco la forma fisica se asocia con menor mortalidad. Para empezar, caminar mas vivo varias veces por semana es una meta realista.',
 null,
 'Lectura breve cuando quieras entender el por que',
 'JAMA Network Open',
 'https://jamanetwork.com/journals/jamanetworkopen',
 array['heart','all'], 'heart', 'any', 'es', 4, false),
('article',
 'Sarcopenia: musculo y autonomia',
 'La perdida de musculo con la edad esta relacionada con caidas, hospitalizaciones y perdida de independencia. Proteina y resistencia son la base practica.',
 null,
 'Leer antes de elegir ejercicio',
 'Journal of Cachexia, Sarcopenia and Muscle',
 'https://link.springer.com/journal/13539',
 array['falls','strength','all'], 'strength', 'any', 'es', 4, false),
('article',
 'Sueno profundo y limpieza cerebral',
 'Durante el sueno profundo, el cerebro consolida memoria y regula residuos metabolicos. La regularidad del horario importa mucho.',
 null,
 'Leer por la tarde, no en la cama',
 'Science',
 'https://www.science.org',
 array['alzheimers','brain','sleep','all'], 'calm', 'any', 'es', 4, false),
('article',
 'Conexion social como salud',
 'El aislamiento social se asocia con peor salud y mayor mortalidad. La voz, la rutina y la pertenencia son parte del plan de bienestar.',
 null,
 'Leer antes de llamar a alguien',
 'PLOS Medicine',
 'https://journals.plos.org/plosmedicine',
 array['alzheimers','anxiety','social','all'], 'calm', 'any', 'es', 4, false),
('article',
 'Aceite de oliva y dieta mediterranea',
 'La evidencia de patrones mediterraneos apoya aceite de oliva virgen extra, legumbres, pescado, frutos secos y verduras como conjunto.',
 null,
 'Leer antes de la compra semanal',
 'New England Journal of Medicine',
 'https://www.nejm.org',
 array['heart','diabetes','all'], 'heart', 'any', 'es', 4, false),
('article',
 'Actividad fisica y demencia',
 'La actividad fisica regular se mantiene como una de las estrategias modificables mas importantes para apoyar cerebro y autonomia.',
 null,
 'Leer cuando planifiques movimiento',
 'The Lancet Commission on Dementia Prevention',
 'https://www.thelancet.com/commissions/dementia-prevention-intervention-care',
 array['alzheimers','brain','all'], 'brain', 'any', 'es', 4, false),
('article',
 'Diversidad vegetal y microbioma',
 'Una dieta con mas variedad de plantas se asocia con microbioma mas diverso. Variedad significa muchas pequenas fuentes, no platos complicados.',
 null,
 'Leer antes de hacer lista de compra',
 'Cell Host and Microbe',
 'https://www.cell.com/cell-host-microbe',
 array['nourishment','all'], 'nourishment', 'any', 'es', 3, false),
('article',
 'Inflamacion de bajo grado en envejecimiento',
 'La inflamacion cronica de bajo grado aparece en muchas rutas de envejecimiento. Movimiento, patron mediterraneo y descanso son palancas seguras.',
 null,
 'Leer cuando quieras contexto general',
 'Nature Reviews Immunology',
 'https://www.nature.com/nri',
 array['heart','alzheimers','diabetes','all'], 'heart', 'any', 'es', 3, false),
('article',
 'Proposito y salud cognitiva',
 'Tener una razon concreta para el dia puede apoyar rutina, animo y participacion social. No tiene que ser grande para ser real.',
 null,
 'Leer al empezar la manana',
 'JAMA Psychiatry',
 'https://jamanetwork.com/journals/jamapsychiatry',
 array['alzheimers','anxiety','brain','all'], 'brain', 'any', 'es', 3, false),
('article',
 'Proteina distribuida durante el dia',
 'Repartir proteina entre comidas puede apoyar mejor el musculo que concentrarla solo en la cena.',
 null,
 'Leer antes de preparar desayuno',
 'American Journal of Clinical Nutrition',
 'https://academic.oup.com/ajcn',
 array['strength','nourishment','all'], 'nourishment', 'any', 'es', 3, false)
on conflict (content_type, title, language) do update
set description = excluded.description,
    detail_text = excluded.detail_text,
    timing_guidance = excluded.timing_guidance,
    source_label = excluded.source_label,
    source_url = excluded.source_url,
    condition_tags = excluded.condition_tags,
    pillar_tag = excluded.pillar_tag,
    time_of_day = excluded.time_of_day,
    rotation_weight = excluded.rotation_weight,
    is_active = false;
